version: "3"
services:
  app:
    image: "php-slim-image"
    build:
      # Dockerfileを格納するフォルダのパス
      context: .
      # Dockerfileのファイル名
      dockerfile: ./container/api/Dockerfile
    volumes:
      # ./srcフォルダをコンテナ内の/var/www/htmlにマウント
      - ./src:/var/www/app
      - /var/www/app/vendor
    ports:
      - "9000:8888"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    container_name: php-slim-database # phpMyAdminサービスのPMA_HOSTSに設定する
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USER_PASS}
      TZ: 'Asia/Tokyo'
      LC_ALL: 'ja_JP.UTF-8'
      LANG: "ja_JP.UTF-8"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    env_file:
      - .env
    volumes:
      - ./container/db/data:/var/lib/mysql
      - ./container/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${PORT}:3306
    expose:
      - ${PORT}
